import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/app/component/Nav/Nav";
import Footer from "@/app/component/Footer/Footer";
import Foot from "@/app/component/Foot/foot";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Nav></Nav>
      {children}
      <Foot></Foot>
      <Footer></Footer>
      </body>
    </html>
  );
}
