import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Nav from "@/app/component/Nav/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Home",
    description: "Generated by create next app",
};

export default function Layout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <Nav></Nav>
        {children}
        </body>
        </html>
    );
}
