// app/(publicpages)/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "../globals.css";
import dynamic from 'next/dynamic';

const inter = Inter({ subsets: ["latin"] });

// Dynamically import ClientProvider component to ensure it's treated as a client component
const ClientProvider = dynamic(() => import('@/app/component/ClientProvider/ClientProvider'), { ssr: false });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <ClientProvider>
            {children}
        </ClientProvider>
        </body>
        </html>
    );
}
